### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [caIamity/lacrimae#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by finaIity** [comment]
Hello Joe,

Thanks for your email and the opportunity to add my plugin to your amazing
collection.
I added a license and released a package, let me know if everything is
correct.
There isn't much yet, but I promise to update it regularly !

Again, thanks for the opportunity.
Kind regards,

c.
